name: Setup
description: Setup Node.js and pnpm

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm

    - name: Install dependencies
      uses: pnpm/action-setup@v2
      with:
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
