name: CI

on:
  push:
  workflow_dispatch:

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm lint

  typechecking:
    name: Typechecking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm tsc

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: node:18
    services:
      database:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - run: pnpm test
        env:
          DB_HOST: database
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: postgres
